import { useState } from "react"

type Screen = "welcome" | "browse" | "post" | "requests" | "alerts" | "profile" | "admin" | "detail"

const food = [
  { id: 1, name: "Dhaka Shahi Kacchi Biryani with Aloo & Egg", quantity: "~20 portions", place: "Tejgaon Link Road, near Shanta Western Tower, Dhaka", time: "Today until 7 PM", status: "Available", image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=900&h=620&fit=crop&auto=format", owner: "MD. Sajjadul Islam", note: "Slow-cooked mutton dum biryani with whole potatoes and boiled eggs. Full trays available.", category: "Biryani & Rice", urgent: true },
  { id: 2, name: "Bhuna Khichuri & Beef Rezala", quantity: "~15 servings", place: "Ahsanullah University Road, Tejgaon I/A, Dhaka", time: "Pickup by 8 PM tonight", status: "Pending", image: "https://images.unsplash.com/photo-1630409349416-24884761a307?w=900&h=620&fit=crop&auto=format", owner: "MD. Fardeen Alam Maruf", note: "Rainy-day khichuri with rich beef rezala gravy. Containers provided.", category: "Hot Meals" },
  { id: 3, name: "Festive Morog Polao & Spiced Dim Roast", quantity: "~12 servings", place: "7 Kunipara, Tejgaon, Dhaka", time: "This evening, before Maghrib", status: "Available", image: "https://images.unsplash.com/photo-1742599361451-3f6608b212f0?w=900&h=620&fit=crop&auto=format", owner: "Zarin Saima", note: "Leftover from a family dawat. Fragrant chicken polao with spiced egg roast.", category: "Festive Dishes" },
  { id: 4, name: "Traditional Shorshe Ilish with Steamed Rice", quantity: "~10 portions", place: "Farmgate – Tejgaon Overpass, Dhaka", time: "Available NOW — 5 PM cutoff", status: "Available", image: "https://images.unsplash.com/photo-1654863404432-cac67587e25d?w=900&h=620&fit=crop&auto=format", owner: "MD. Fardeen Alam Maruf", note: "Hilsa in mustard-turmeric gravy. Freshly made, rice included. Bring your own container.", category: "Fish & Seafood", urgent: true },
  { id: 5, name: "Traditional Mishti Platter — Sondesh", quantity: "~30 pieces", place: "Nabisco Mor, Shaheed Tajuddin Ahmed Ave, Tejgaon, Dhaka", time: "Anytime today", status: "Accepted", image: "https://images.unsplash.com/photo-1695568181363-af5c78f4d059?w=900&h=620&fit=crop&auto=format", owner: "Zarin Saima", note: "Surplus from Eid celebration. Kept chilled. Mix of chomchom and rosogolla.", category: "Sweets & Mishti" },
  { id: 6, name: "Crispy Fuchka & Tangy Spiced Chotpoti", quantity: "~50 pieces + 2 kg chotpoti", place: "Tejgaon Commercial Area, Link Road, Dhaka", time: "Today 4–6 PM only", status: "Available", image: "https://images.unsplash.com/photo-1614435842039-e842b002c342?w=900&h=620&fit=crop&auto=format", owner: "MD. Sajjadul Islam", note: "Street-style fuchka shells and a big batch of chotpoti with tamarind water. Serve yourself.", category: "Street Food" },
]

const Icon = ({ name, size = 20 }: { name: string; size?: number }) => {
  const paths: Record<string, string> = {
    home: "M3 10.8 12 3l9 7.8v9.7a.5.5 0 0 1-.5.5h-5.7v-6H9.2v6H3.5a.5.5 0 0 1-.5-.5z", plus: "M12 5v14M5 12h14", heart: "M20.8 5.8a5.5 5.5 0 0 0-7.8 0L12 7l-1-1.2a5.5 5.5 0 0 0-7.8 7.8L12 22l8.8-8.4a5.5 5.5 0 0 0 0-7.8z", bell: "M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4", user: "M20 21a8 8 0 0 0-16 0M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", search: "m21 21-4.3-4.3M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0z", pin: "M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0zM12 12a2 2 0 1 0 0-4 2 2 0 0 0 0 4z", arrow: "M5 12h14m-6-6 6 6-6 6", leaf: "M20 4C10 4 4 9 4 17c0 2 1 3 3 3 8 0 13-6 13-16ZM4 20c3-5 7-8 12-10", menu: "M4 7h16M4 12h16M4 17h16", close: "m6 6 12 12M18 6 6 18", check: "m5 12 4 4L19 6", clock: "M12 7v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0", camera: "M4 7h3l1.5-2h7L17 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2zm8 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", users: "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.8M16 3.2a4 4 0 0 1 0 7.6",
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]} /></svg>
}

function Badge({ status }: { status: string }) { return <span className={`badge badge-${status.toLowerCase()}`}>{status}</span> }
function FoodCard({ item, onClick }: { item: typeof food[0]; onClick: () => void }) { return <button onClick={onClick} className={`food-card text-left ${item.urgent ? "urgent" : ""}`}><div className="relative h-43 overflow-hidden bg-[#dfe7d8]"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 hover:scale-105"/><Badge status={item.status}/></div><div className="p-4"><p className="food-category">{item.category}</p><h3>{item.name}</h3><p className="quantity">{item.quantity}</p><div className="meta"><span><Icon name="pin" size={14}/>{item.place}</span><span><Icon name="clock" size={14}/>{item.time}</span></div></div></button> }

export default function App() {
  const [screen, setScreen] = useState<Screen>("welcome")
  const [selected, setSelected] = useState(food[0])
  const [search, setSearch] = useState("")
  const [requestTab, setRequestTab] = useState<"sent" | "received">("sent")
  const [menuOpen, setMenuOpen] = useState(false)
  const go = (next: Screen) => { setScreen(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }) }
  const openDetail = (item: typeof food[0]) => { setSelected(item); go("detail") }
  const filtered = food.filter(x => x.name.toLowerCase().includes(search.toLowerCase()) || x.category.toLowerCase().includes(search.toLowerCase()))
  const nav = [{ id: "browse", label: "Explore", icon: "home" }, { id: "post", label: "Share food", icon: "plus" }, { id: "requests", label: "Requests", icon: "heart" }, { id: "alerts", label: "Alerts", icon: "bell" }, { id: "profile", label: "Profile", icon: "user" }] as {id: Screen; label: string; icon: string}[]

  if (screen === "welcome") return <main className="welcome"><header className="landing-head"><button className="brand" onClick={() => go("welcome")}><span><Icon name="leaf" size={22}/></span>shareplate</button><div className="head-actions"><button className="text-button" onClick={() => go("browse")}>Log in</button><button className="button button-dark" onClick={() => go("browse")}>Join the table <Icon name="arrow" size={17}/></button></div></header><section className="hero"><div className="hero-copy"><p className="eyebrow"><span/> A kinder way to eat</p><h1>Good food<br/><em>belongs</em> on plates.</h1><p className="lede">Share extra meals with your neighbours. Less waste in the bin, more good around the table.</p><div className="hero-actions"><button className="button button-primary" onClick={() => go("browse")}>Find food nearby <Icon name="arrow" size={17}/></button><button className="button button-quiet" onClick={() => go("post")}>Share your surplus</button></div><div className="hero-proof"><div className="avatars"><i>AM</i><i>JN</i><i>LC</i><i>+</i></div><span>Joined by <strong>2,400+ neighbours</strong><br/>in sharing what they have.</span></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?w=1300&h=1500&fit=crop&auto=format" alt="Friends sharing a colourful meal"/><div className="floating-note"><span className="note-icon"><Icon name="heart" size={18}/></span><b>Today, 186 meals</b><small>found a home nearby</small></div><span className="sun"></span></div></section><section className="how"><p className="eyebrow">A simple, local circle</p><h2>More sharing. Less <em>throwing away.</em></h2><div className="steps"><div><span>01</span><h3>Post what’s extra</h3><p>A few portions or a whole catering tray—let neighbours know.</p></div><div><span>02</span><h3>Find food nearby</h3><p>Browse fresh posts from people and places in your area.</p></div><div><span>03</span><h3>Pass it forward</h3><p>Collect with a smile and keep good food in the community.</p></div></div></section></main>

  return <div className="app-shell"><aside className="sidebar"><button className="brand side-brand" onClick={() => go("browse")}><span><Icon name="leaf" size={21}/></span>shareplate</button><p className="sidebar-label">Community board</p><nav>{nav.map(item => <button key={item.id} onClick={() => go(item.id)} className={screen === item.id || (screen === "detail" && item.id === "browse") ? "active" : ""}><Icon name={item.icon}/>{item.label}{item.id === "alerts" && <b className="dot"/>}</button>)}</nav><div className="sidebar-bottom"><button onClick={() => go("admin")}><Icon name="users"/>Admin space</button><div className="mini-user"><div>SI</div><span><b>MD. Sajjadul Islam</b><small>Tejgaon Community</small></span></div></div></aside><header className="mobile-head"><button className="brand" onClick={() => go("browse")}><span><Icon name="leaf" size={19}/></span>shareplate</button><button className="round-button" onClick={() => setMenuOpen(!menuOpen)}><Icon name={menuOpen ? "close" : "menu"}/></button>{menuOpen && <nav className="mobile-menu">{nav.map(item => <button key={item.id} onClick={() => go(item.id)}><Icon name={item.icon}/>{item.label}</button>)}</nav>}</header><main className="content">{screen === "browse" && <><div className="page-title"><div><p className="eyebrow">Tejgaon community board</p><h1>What’s nearby <span>✦</span></h1><p>There are <b>6 fresh shares</b> within 2 km today.</p></div><button className="button button-primary desktop-add" onClick={() => go("post")}><Icon name="plus" size={18}/> Share food</button></div><div className="search-row"><div className="search"><Icon name="search"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search food near you…"/></div><button className="location"><Icon name="pin" size={17}/> Tejgaon, Dhaka · 2 km</button><button className="filter">Filters <span>2</span></button></div><div className="nearby-head"><div><h2>On the community board</h2><p>Collect before these lovely things disappear.</p></div><button className="see-all">See all <Icon name="arrow" size={16}/></button></div>{filtered.length ? <div className="food-grid">{filtered.map(item => <FoodCard key={item.id} item={item} onClick={() => openDetail(item)}/>)}</div> : <div className="empty"><div>⌕</div><h2>Nothing on the corkboard</h2><p>Try another food name or category.</p></div>}</>}
  {screen === "detail" && <div className="detail"><button className="back" onClick={() => go("browse")}>← Back to nearby food</button><div className="detail-grid"><div><div className="detail-image"><img src={selected.image} alt={selected.name}/><Badge status={selected.status}/></div><div className="owner-card"><div className="owner-avatar">{selected.owner.slice(0, 1)}</div><div><p>Shared by</p><b>{selected.owner}</b><small>Verified community member</small></div><button>View profile</button></div></div><article><p className="eyebrow">Available today</p><h1>{selected.name}</h1><p className="detail-quantity">{selected.quantity} ready to collect</p><p className="detail-copy">{selected.note}</p><dl><div><dt><Icon name="pin"/> Collection point</dt><dd>{selected.place.replace(" ·", "")}</dd></div><div><dt><Icon name="clock"/> Pickup window</dt><dd>Today · 5:30 – 7:00 PM</dd></div></dl><button className="button button-primary request" onClick={() => go("requests")}>Request this food <Icon name="arrow" size={18}/></button><p className="fine">You’ll only share contact details once the request is accepted.</p></article></div></div>}
  {screen === "post" && <div className="form-page"><div className="page-title"><div><p className="eyebrow">Share the good stuff</p><h1>Post surplus food</h1><p>A little detail helps the right neighbour find it.</p></div></div><form className="post-form" onSubmit={e => {e.preventDefault(); go("browse")}}><div className="photo-upload"><Icon name="camera" size={28}/><b>Add a photo</b><span>Take one or choose from your library</span><input type="file" aria-label="Upload food photo"/></div><label>What are you sharing?<input placeholder="e.g. Bhuna khichuri" required/></label><div className="form-two"><label>How much?<input placeholder="e.g. 12 servings" required/></label><label>Collection time<select defaultValue=""><option value="" disabled>Select a window</option><option>Today until 7 PM</option><option>Pickup by 8 PM tonight</option><option>This evening, before Maghrib</option></select></label></div><label>Collection location<input placeholder="e.g. Tejgaon Link Road, Dhaka" required/></label><label>A helpful note <textarea placeholder="Ingredients, collection details, anything useful…" rows={3}/></label><div className="form-actions"><button type="button" className="button button-quiet" onClick={() => go("browse")}>Cancel</button><button className="button button-primary" type="submit">Publish food post <Icon name="arrow" size={17}/></button></div></form></div>}
  {screen === "requests" && <div className="form-page requests"><div className="page-title"><div><p className="eyebrow">Keep the circle moving</p><h1>Requests</h1><p>Manage food you’ve asked for and shared.</p></div></div><div className="tabs"><button className={requestTab === "sent" ? "chosen" : ""} onClick={() => setRequestTab("sent")}>Sent <span>1</span></button><button className={requestTab === "received" ? "chosen" : ""} onClick={() => setRequestTab("received")}>Received <span>2</span></button></div>{requestTab === "sent" ? <div className="request-list"><RequestRow image={food[4].image} title="Traditional Mishti Platter" person="You → Zarin Saima · Yesterday" status="Accepted"/></div> : <div className="request-list"><RequestRow image="https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=160&h=160&fit=crop&auto=format" title="MD. Fardeen Alam Maruf requested your biryani" person="For your Dhaka Shahi Kacchi Biryani · 2h ago" status="Pending" actions/><RequestRow image="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&h=160&fit=crop&auto=format" title="Zarin Saima requested your khichuri" person="For your Bhuna Khichuri & Beef Rezala · 30 min ago" status="Pending" actions/></div>}</div>}
  {screen === "alerts" && <div className="form-page"><div className="page-title"><div><p className="eyebrow">Stay in the loop</p><h1>Notifications</h1></div><button className="text-button">Mark all read</button></div><div className="alerts"><Alert icon="check" title="Your request for Traditional Mishti Platter was accepted" text="Zarin Saima has accepted your request." fresh/><Alert icon="heart" title="MD. Fardeen Alam Maruf requested your biryani" text="They’ve asked for your Dhaka Shahi Kacchi Biryani post." fresh/><Alert icon="leaf" title="New post near Tejgaon Link Road" text="Festive Morog Polao & Spiced Dim Roast is now available."/><Alert icon="clock" title="Your biryani post expires soon" text="Dhaka Shahi Kacchi Biryani expires in 2 hours."/></div></div>}
  {screen === "profile" && <div className="form-page"><div className="profile-hero"><div className="profile-avatar">SI</div><div><Badge status="Household"/><h1>MD. Sajjadul Islam</h1><p>Tejgaon Community · Dhaka</p></div><button className="button button-quiet">Edit profile</button></div><div className="profile-stats"><div><b>12</b><span>Posts</span></div><div><b>34 kg</b><span>Shared</span></div><div><b>8</b><span>Requests</span></div></div><section className="profile-section"><p className="eyebrow">Your recent shares</p><h2>Made with care, shared with care</h2><div className="my-post"><img src={food[0].image} alt="Dhaka Shahi Kacchi Biryani"/><div><Badge status="Available"/><h3>Dhaka Shahi Kacchi Biryani</h3><p>~20 portions · Today until 7 PM</p></div><button className="text-button">Manage</button></div></section></div>}
  {screen === "admin" && <div className="admin"><div className="page-title"><div><p className="eyebrow">Moderation desk</p><h1>Community health</h1><p>A calm overview of SharePlate today.</p></div><button className="button button-quiet" onClick={() => go("browse")}>Exit admin</button></div><div className="stat-grid"><Stat number="2,481" label="Total members"/><Stat number="186" label="Active food posts"/><Stat number="74" label="Requests today"/></div><section className="table-wrap"><div className="table-title"><h2>Recent food posts</h2><button className="see-all">Review queue <Icon name="arrow" size={16}/></button></div><table><thead><tr><th>Post</th><th>Shared by</th><th>Status</th><th></th></tr></thead><tbody>{food.slice(0,3).map(f => <tr key={f.id}><td><b>{f.name}</b><small>{f.quantity}</small></td><td>{f.owner}</td><td><Badge status={f.status}/></td><td><button className="text-button">Remove</button></td></tr>)}</tbody></table></section></div>}</main><nav className="bottom-nav">{nav.map(item => <button key={item.id} onClick={() => go(item.id)} className={screen === item.id ? "active" : ""}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav></div>
}

function RequestRow({ image, title, person, status, actions }: {image:string;title:string;person:string;status:string;actions?:boolean}) { return <article className="request-row"><img src={image} alt=""/><div><Badge status={status}/><h3>{title}</h3><p>{person}</p></div>{actions ? <div className="request-actions"><button className="button button-quiet">Reject</button><button className="button button-primary">Accept</button></div> : <button className="text-button">View details</button>}</article> }
function Alert({ icon, title, text, fresh }: {icon:string;title:string;text:string;fresh?:boolean}) { return <article className={`alert ${fresh ? "fresh" : ""}`}><span className="alert-icon"><Icon name={icon}/></span><div><h3>{title}</h3><p>{text}</p><small>{fresh ? "Just now" : "Earlier today"}</small></div>{fresh && <i/>}</article> }
function Stat({number,label}:{number:string;label:string}) { return <div className="stat"><b>{number}</b><span>{label}</span><em>↗ 8.4%</em></div> }
